name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  ci-core:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/core
    timeout-minutes: 3
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-core
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: pnpm setup
        uses: pnpm/action-setup@903f9c1a6ebcba6cf41d87230be49611ac97822e # v6.0.3

      - name: Install dependencies
        run: pnpm install

      - name: Lint
        run: pnpm run lint

      - name: Test
        run: pnpm run test

  ci-web:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/web
    timeout-minutes: 3
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-web
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: pnpm setup
        uses: pnpm/action-setup@903f9c1a6ebcba6cf41d87230be49611ac97822e # v6.0.3

      - name: Install dependencies
        run: pnpm install

      - name: Lint
        run: pnpm run lint

      - name: Build
        run: pnpm run build